// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;
using UniRx;


[DiagramInfoAttribute("NewProjectRepository")]
public abstract class BirdViewBase : ViewBase {
    
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public BirdState _State;
    
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Single _MaxSpeed;
    
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Single _FlapVelocity;
    
    public override System.Type ViewModelType {
        get {
            return typeof(BirdViewModel);
        }
    }
    
    public BirdViewModel Bird {
        get {
            return ((BirdViewModel)(this.ViewModelObject));
        }
        set {
            this.ViewModelObject = value;
        }
    }
    
    public override ViewModel CreateModel() {
        return this.RequestViewModel(GameManager.Container.Resolve<BirdController>());
    }
    
    protected override void InitializeViewModel(ViewModel viewModel) {
        BirdViewModel bird = ((BirdViewModel)(viewModel));
        bird.State = this._State;
        bird.MaxSpeed = this._MaxSpeed;
        bird.FlapVelocity = this._FlapVelocity;
    }
    
    public virtual void ExecuteHit() {
        this.ExecuteCommand(Bird.Hit);
    }
}

[DiagramInfoAttribute("NewProjectRepository")]
public abstract class PipeViewBase : ViewBase {
    
    public override System.Type ViewModelType {
        get {
            return typeof(PipeViewModel);
        }
    }
    
    public PipeViewModel Pipe {
        get {
            return ((PipeViewModel)(this.ViewModelObject));
        }
        set {
            this.ViewModelObject = value;
        }
    }
    
    public override ViewModel CreateModel() {
        return this.RequestViewModel(GameManager.Container.Resolve<PipeController>());
    }
    
    protected override void InitializeViewModel(ViewModel viewModel) {
    }
    
    public virtual void ExecutePassed() {
        this.ExecuteCommand(Pipe.Passed);
    }
    
    public virtual void ExecuteRemoveFromScreen() {
        this.ExecuteCommand(Pipe.RemoveFromScreen);
    }
}

[DiagramInfoAttribute("NewProjectRepository")]
public abstract class AngryFlappersGameViewBase : ViewBase {
    
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public ViewBase _Bird;
    
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public AngryFlappersGameState _State;
    
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _Score;
    
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Single _Gravity;
    
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Single _PipeSpawnSeed;
    
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Single _ScrollSpeed;
    
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _Try;
    
    public override string DefaultIdentifier {
        get {
            return "AngryFlappersGame";
        }
    }
    
    public override System.Type ViewModelType {
        get {
            return typeof(AngryFlappersGameViewModel);
        }
    }
    
    public AngryFlappersGameViewModel AngryFlappersGame {
        get {
            return ((AngryFlappersGameViewModel)(this.ViewModelObject));
        }
        set {
            this.ViewModelObject = value;
        }
    }
    
    public override ViewModel CreateModel() {
        return this.RequestViewModel(GameManager.Container.Resolve<AngryFlappersGameController>());
    }
    
    protected override void InitializeViewModel(ViewModel viewModel) {
        AngryFlappersGameViewModel angryFlappersGame = ((AngryFlappersGameViewModel)(viewModel));
        angryFlappersGame.Bird = this._Bird == null ? null : this._Bird.ViewModelObject as BirdViewModel;
        angryFlappersGame.State = this._State;
        angryFlappersGame.Score = this._Score;
        angryFlappersGame.Gravity = this._Gravity;
        angryFlappersGame.PipeSpawnSeed = this._PipeSpawnSeed;
        angryFlappersGame.ScrollSpeed = this._ScrollSpeed;
        angryFlappersGame.Try = this._Try;
    }
    
    public virtual void ExecuteGameOver() {
        this.ExecuteCommand(AngryFlappersGame.GameOver);
    }
    
    public virtual void ExecutePlay() {
        this.ExecuteCommand(AngryFlappersGame.Play);
    }
    
    public virtual void ExecuteGoToMenu() {
        this.ExecuteCommand(AngryFlappersGame.GoToMenu);
    }
}

[DiagramInfoAttribute("NewProjectRepository")]
public abstract class MenuRootViewBase : ViewBase {
    
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _Score;
    
    public override string DefaultIdentifier {
        get {
            return "MenuRoot";
        }
    }
    
    public override System.Type ViewModelType {
        get {
            return typeof(MenuRootViewModel);
        }
    }
    
    public MenuRootViewModel MenuRoot {
        get {
            return ((MenuRootViewModel)(this.ViewModelObject));
        }
        set {
            this.ViewModelObject = value;
        }
    }
    
    public override ViewModel CreateModel() {
        return this.RequestViewModel(GameManager.Container.Resolve<MenuRootController>());
    }
    
    protected override void InitializeViewModel(ViewModel viewModel) {
        MenuRootViewModel menuRoot = ((MenuRootViewModel)(viewModel));
        menuRoot.Score = this._Score;
    }
    
    public virtual void ExecuteGoToGame() {
        this.ExecuteCommand(MenuRoot.GoToGame);
    }
}

public class AngryFlappersGameViewViewBase : AngryFlappersGameViewBase {
    
    [UFToggleGroup("State")]
    [UnityEngine.HideInInspector()]
    [UFRequireInstanceMethod("StateChanged")]
    public bool _BindState = true;
    
    [UFToggleGroup("Score")]
    [UnityEngine.HideInInspector()]
    [UFRequireInstanceMethod("ScoreChanged")]
    public bool _BindScore = true;
    
    [UFToggleGroup("Pipes")]
    [UnityEngine.HideInInspector()]
    public bool _BindPipes = true;
    
    [UFGroup("Pipes")]
    [UnityEngine.HideInInspector()]
    public bool _PipesSceneFirst;
    
    [UFGroup("Pipes")]
    [UnityEngine.HideInInspector()]
    public UnityEngine.Transform _PipesContainer;
    
    public override ViewModel CreateModel() {
        return this.RequestViewModel(GameManager.Container.Resolve<AngryFlappersGameController>());
    }
    
    /// Subscribes to the property and is notified anytime the value changes.
    public virtual void StateChanged(AngryFlappersGameState value) {
    }
    
    /// Subscribes to the property and is notified anytime the value changes.
    public virtual void ScoreChanged(Int32 value) {
    }
    
    /// This binding will add or remove views based on an element/viewmodel collection.
    public virtual ViewBase CreatePipesView(PipeViewModel item) {
        return this.InstantiateView(item);
    }
    
    /// This binding will add or remove views based on an element/viewmodel collection.
    public virtual void PipesAdded(ViewBase item) {
    }
    
    /// This binding will add or remove views based on an element/viewmodel collection.
    public virtual void PipesRemoved(ViewBase item) {
    }
    
    public override void Bind() {
        base.Bind();
        if (this._BindState) {
            this.BindProperty(AngryFlappersGame._StateProperty, this.StateChanged);
        }
        if (this._BindScore) {
            this.BindProperty(AngryFlappersGame._ScoreProperty, this.ScoreChanged);
        }
        if (this._BindPipes) {
            this.BindToViewCollection( AngryFlappersGame._PipesProperty, viewModel=>{ return CreatePipesView(viewModel as PipeViewModel); }, PipesAdded, PipesRemoved, _PipesContainer, _PipesSceneFirst);
        }
    }
}

public partial class AngryFlappersGameView : AngryFlappersGameViewViewBase {
}

public class GroundViewViewBase : AngryFlappersGameViewBase {
    
    public override ViewModel CreateModel() {
        return this.RequestViewModel(GameManager.Container.Resolve<AngryFlappersGameController>());
    }
    
    public override void Bind() {
        base.Bind();
    }
}

public partial class GroundView : GroundViewViewBase {
}

public class PipeViewViewBase : PipeViewBase {
    
    public override ViewModel CreateModel() {
        return this.RequestViewModel(GameManager.Container.Resolve<PipeController>());
    }
    
    public override void Bind() {
        base.Bind();
    }
}

public partial class PipeView : PipeViewViewBase {
}

public class BirdViewViewBase : BirdViewBase {
    
    [UFToggleGroup("State")]
    [UnityEngine.HideInInspector()]
    [UFRequireInstanceMethod("StateChanged")]
    public bool _BindState = true;
    
    public override ViewModel CreateModel() {
        return this.RequestViewModel(GameManager.Container.Resolve<BirdController>());
    }
    
    /// Subscribes to the property and is notified anytime the value changes.
    public virtual void StateChanged(BirdState value) {
    }
    
    public override void Bind() {
        base.Bind();
        if (this._BindState) {
            this.BindProperty(Bird._StateProperty, this.StateChanged);
        }
    }
}

public partial class BirdView : BirdViewViewBase {
}

public class MenuRootViewViewBase : MenuRootViewBase {
    
    [UFToggleGroup("Score")]
    [UnityEngine.HideInInspector()]
    [UFRequireInstanceMethod("ScoreChanged")]
    public bool _BindScore = true;
    
    public override ViewModel CreateModel() {
        return this.RequestViewModel(GameManager.Container.Resolve<MenuRootController>());
    }
    
    /// Subscribes to the property and is notified anytime the value changes.
    public virtual void ScoreChanged(Int32 value) {
    }
    
    public override void Bind() {
        base.Bind();
        if (this._BindScore) {
            this.BindProperty(MenuRoot._ScoreProperty, this.ScoreChanged);
        }
    }
}

public partial class MenuRootView : MenuRootViewViewBase {
}
